<?php
	//includes
	include_once('../templates/tpl_common.php');
	include_once('../templates/tpl_admin.php');
	//page
	drawHead();
	drawHeaderAdmin(0);
    drawAdminStart(NULL);
    drawAdminInterface(1);
    drawAdminProductEdition();
    drawAdminEnd();
	drawAdminFooter(); 
?>