<?php
	//includes
	include_once('../templates/tpl_common.php');
	include_once('../templates/tpl_homepage.php');
	//page
	drawHead();
	drawHeader(0);
	drawNavbar('');
	drawHomepage();
	drawFooter();
?>